spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=GMT%2B8
    username: springuser
    password: ThePassword
  jpa:
    hibernate:
      ddlAuto: none

server:
  servlet:
    context-path: /uaa
  port: 5000
