server:
  port: 8080

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://localhost:5000
      stripPrefix: false


    account-service:
      path: /accounts/**
      serviceId: account-service
      stripPrefix: false


    statistic-service:
      path: /statistics/**
      serviceId: statistic-service
      stripPrefix: false



