security:
  oauth2:
    client:
      clientId: notification-service
      clientSecret: ${NOTIFICATION_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /notifications
  port: 8060

remind:
  cron: 0 0 0 * * *
  email:
    text: "Hey, {0}! We've missed you here on Hukarshu. It's time to check your budget statistics.\r\n\r\nCheers,\r\nHukarshu team"
    subject: Hukarshu reminder

update:
  cron: 0 0 12 * * *
  email:
    text: ""
    subject: Hukarshu updated
    attachment:New version
spring:
  data:
    mongodb:
      host: localhost
      username: springuserRecipient
      password: recipient
      database: recipients
      port: 27017
  mail:
    host: smtp.qq.com
    port: 465
    username: 1475563545
    password: njuni666
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
