server:
  servlet:
    context-path: /statistics
  port: 8040

security:
  oauth2:
    client:
      clientId: statistic-service
      clientSecret: ${STATISTIC_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:5000/uaa/users/current

spring:
  data:
    mongodb:
      host: localhost
      username: springuserStatistic
      password: statistic
      database: statistics
      port: 27017