server:
  servlet:
    context-path: /statistics
  port: 8040

security:
  oauth2:
    client:
      clientId: statistic-service
      clientSecret: ${STATISTIC_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:5000/uaa/users/current

#spring:
#  data:
#    mongodb:
#      uri: mongodb://springuserStatistic:statistic@localhost:27017/?authSource=statistics
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: statistics
#      uri: mongodb://localhost:27017/?authSource=statistics
      username: springuserStatistic
      password: statistic

